'use client';
import { useState } from 'react';

interface Props {
  prData: {
    title: string;
    author: string;
    changedFiles: number;
    additions: number;
    deletions: number;
    baseBranch: string;
    headBranch: string;
  };
  review: {
    summary: string;
    healthScore: number;
    issues: Array<{
      severity: 'CRITICAL' | 'WARNING' | 'SUGGESTION';
      title: string;
      file: string;
      explanation: string;
      fix?: string;
    }>;
    commentsPosted: number;
  };
}

export default function ExportMarkdownButton({ prData, review }: Props) {
  const [loading, setLoading] = useState(false);

  async function handleExport() {
    setLoading(true);
    try {
      const filename = `mergemind-review-${prData.author.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.md`;
      
      // Construct beautiful Markdown content
      const mdContent = `# MergeMinD Code Review Report

## 🎯 Merge Request Details
- **Title**: ${prData.title}
- **Author**: ${prData.author}
- **Files Changed**: ${prData.changedFiles} files (\`+${prData.additions}\` / \`-${prData.deletions}\`)
- **Branch**: \`${prData.baseBranch}\` ← \`${prData.headBranch}\`

---

## 📊 Overall Assessment
- **Health Score**: **${review.healthScore}/10**
- **GitLab Comments Posted**: ${review.commentsPosted}

### Summary
${review.summary}

---

## 🔍 Review Findings (${review.issues.length})

${review.issues.map((issue, index) => {
  let severityEmoji = '💡';
  if (issue.severity === 'CRITICAL') severityEmoji = '🚨';
  else if (issue.severity === 'WARNING') severityEmoji = '⚠️';

  return `### ${index + 1}. ${severityEmoji} [${issue.severity}] ${issue.title}
- **File**: \`${issue.file}\`
- **Description**: ${issue.explanation}
${issue.fix ? `- **Suggested Correction**:
\`\`\`
${issue.fix.trim()}
\`\`\`` : ''}
`;
}).join('\n')}

---
*Report generated by MergeMinD AI — powered by Gemini + GitLab MCP*
`;

      // Trigger native Save File dialog if supported
      if ('showSaveFilePicker' in window) {
        try {
          const handle = await (window as any).showSaveFilePicker({
            suggestedName: filename,
            types: [{
              description: 'Markdown Files',
              accept: { 'text/markdown': ['.md'] },
            }],
          });
          const writable = await handle.createWritable();
          await writable.write(mdContent);
          await writable.close();
          setLoading(false);
          return;
        } catch (err: any) {
          // If user cancelled, just stop loading
          if (err.name === 'AbortError') {
            setLoading(false);
            return;
          }
          console.warn('showSaveFilePicker failed, falling back to anchor download', err);
        }
      }

      // Fallback: Standard browser download (respects browser "Ask where to save" settings)
      const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', filename);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Markdown export error:', err);
      alert('Failed to export Markdown. Please try again.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <button
      onClick={handleExport}
      disabled={loading}
      className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold border border-gray-800 bg-gray-900 text-gray-300 hover:border-orange-500/30 hover:text-orange-400 hover:bg-gray-900/80 transition-all duration-300 cursor-pointer hover:scale-[1.02] active:scale-[0.98] disabled:opacity-50"
    >
      {loading ? (
        <svg className="w-4 h-4 animate-spin text-orange-400" fill="none" viewBox="0 0 24 24">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"/>
        </svg>
      ) : (
        <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
      )}
      {loading ? 'Exporting...' : 'Export Markdown'}
    </button>
  );
}
